### ISSUE TITLE
GoogleMobileAds-v7.0.0 conflict with tapsellplus 2.1.7

### ISSUE THREAD

**Issue by mkfcga** [tapsellorg/TapsellPlusSDK-UnitySample2019#9]
سلام.
ظاهرا فایل های اصلی گوگل اد رو تغییر دادین و اگر بخایم از گوگل اد جدا استفاده کنیم امکانش نیست! آخرین نسخه گوگل, آبجکت UnifiedNativeAd 
 و UnifiedNativeAdEventArgs رو نداره!

Assets\TapsellPlus\TapsellPlusNativeBannerAd.cs(17,26): error CS0246: The type or namespace name 'UnifiedNativeAd' could not be found (are you missing a using directive or an assembly reference?)

Assets\TapsellPlus\TapsellPlus.cs(273,74): error CS0246: The type or namespace name 'UnifiedNativeAdEventArgs' could not be found (are you missing a using directive or an assembly reference?)

اگر از گوگل موبایل اد پروژه شما استفاده کنم دیگه نمیشه گوگل اد رو اینیشال کرد.
خطای اینیشال گوگل وقتی از پکیج شما استفاده میکنم:
2022-04-23 10:27:17.724 13028-13069/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
    java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.ads.initialization.OnInitializationCompleteListener
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0) 
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:246) 
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20) 
      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <000000000000000000000

**Comment by mahdi-malv** [comment]
سلام
ممنون که اطلاع دادید این مورد رو
بله این باگ وجود داره و باید lite admob توی تپسل آپدیت بشه

من این مورد رو به همکاران اطلاع میدم که در اسرع وقت مرتفعش کنن
توی ریلیز بعدی فیکس خواهد شد

لطفا این ایشو باز بمونه و هنگام رفع مشکل و پکیج جدید (اولین آلفا ریلیز)، ایشو آپدیت خواهد شد

با تشکر

**Comment by MortezaNedaei** [comment]
این مشکل در نسخه [v2.1.8-alpha02](https://github.com/tapsellorg/TapsellPlusSDK-UnityPlugin/releases/tag/v2.1.8-alpha02) آلفا حل شد.

**Comment by mostafabandbafiha** [comment]
سلام برای من همچنان مشکل داره هم با نسخه 7 admob هم نسخه 7.1

**Comment by MortezaNedaei** [comment]
> سلام برای من همچنان مشکل داره هم با نسخه 7 admob هم نسخه 7.1

سلام از کدوم نسخه تپسل استفاده می‌کنید؟

**Comment by mostafabandbafiha** [comment]
هم از نسخه 2.1.7 هم همین نسخه 2.1.8 الفا 
فقط من اول تپسل رو راه اندازی کردم بدون مشکل هم هست کار می کنه ولی می خواستم admob اضافه کنم که وقتی یونیتی پکیج گوگل رو ایمپورت می کنم همین خطا رو می ده روند کار رو اشتباه انجام می دم؟

**Comment by mkfcga** [comment]
همچنان مشکل داره. 
admob 7.1.0
tapsell 2.1.8 alpha2

Assets\TapsellPlusSDK\TapsellPlus.cs(277,74): error CS0246: The type or namespace name 'NativeAdEventArgs' could not be found (are you missing a using directive or an assembly reference?)
Assets\TapsellPlusSDK\TapsellPlusNativeBannerAd.cs(11,26): error CS0246: The type or namespace name 'NativeAd' could not be found (are you missing a using directive or an assembly reference?)
Assets\TapsellPlusSDK\TapsellPlusNativeBannerAd.cs(24,34): error CS0246: The type or namespace name 'NativeAd' could not be found (are you missing a using directive or an assembly reference?)

**Comment by MortezaNedaei** [comment]
کتابخانه ادموب، در نسخه های آخرش تغییراتی داخل پکیج هاش اعمال کرده. برای رفع مشکل بیلد، می‌تونید کتابخانه ادموب لایت تپسل (سازگار با Admob 7.1) رو هم بعد از پکیج یونیتی تپسل، به پروژه اضافه کنید که در این [لینک](https://github.com/tapsellorg/TapsellPlusSDK-UnityPlugin/releases/tag/v2.1.8-alpha03) وجود داره.

[لینک دانلود کتابخانه تپسل نسخه‌ی v2.1.8-alpha02](https://github.com/tapsellorg/TapsellPlusSDK-UnityPlugin/releases/download/v2.1.8-alpha03/tapsell-plus-unity-2.1.8-alpha03.unitypackage)
[لینک دانلود کتابخانه admob-lite سازگار با Admob 7.1](https://github.com/tapsellorg/TapsellPlusSDK-UnityPlugin/releases/download/v2.1.8-alpha03/tapsell-plus-admob-lite-v7.1.0.unitypackage)

@mkfcga @mostafabandbafiha

**Comment by mkfcga** [comment]
نسخه اندروید رو تست نکردم. اما ios مشکل بیلد داریم.
اگر فقط از admob7.1.0 استفاده بشه هیچ خطایی در بیلد نیست.
اما از آلفا 3 و lite که استفاده کردیم. با اینکه خطای ادیتور نداریم اما نمیشه بیلد گرفت.
xcode:13.4.1
خطای بیلد:
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/build/Desktop/**/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_GADUNativeAdCallToAction", referenced from:
      __5cABXlEfG0XrM4WXXDifxKEqMEo_GetCallToAction_mFEED7465E689FFE18BCA3ABB8D974FA9EB733473 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__WBjHLdy0u2OPvLcberYaz4E5lkm_mE2ABAA9E65C0BF7B227E1D80394AA6BFABAF5698 in GoogleMobileAdsNative.iOS.o
  "_GADUNativeAdBody", referenced from:
      __5cABXlEfG0XrM4WXXDifxKEqMEo_GetBody_mAFCDF87B0A649EC6356A9FB5C68B1C61F3D5720D in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__uWrZG4X0g4xz7ZcWN7vkHw29uHg_mA43438D1516D5E2A9C8151D4380A040031417955 in GoogleMobileAdsNative.iOS.o
  "_GADUNativeAdHeadline", referenced from:
      __5cABXlEfG0XrM4WXXDifxKEqMEo_GetHeadline_m1C13883E29B9F055612901F5E51051B267D4206A in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__WDCDUwJ5OfEKCY0Io3ukTaT2eSH_mA0193BF6186429BFDA921BEBC6B04190B4E4071C in GoogleMobileAdsNative.iOS.o
  "_GADUNativeAdMainImagesURLs", referenced from:
      __5cABXlEfG0XrM4WXXDifxKEqMEo_GetMainImageURLs_m30F69E4F117F035EA7D7F320DC7C3EED7A4EE6D6 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__t7yhA3nJYckCEyX1l0SAL51ip23_mEC61A2A9554853B99B04777B239096371696E648 in GoogleMobileAdsNative.iOS.o
  "_GADUCustomNativeAdFormatID", referenced from:
      __V1fgpHIlEfdgcIGdMwPd9AxlM8B_GetFormatId_m6D1516F2B74C42853B37AFBEEA07F4553133568F in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__YciJAsA6I19uIJP6mPVBeYyFmDj_m8A3AEFC12F50476C6BCF7D41C8364B9F3E14E998 in GoogleMobileAdsNative.iOS.o
  "_GADUPerformClickOnNativeAd", referenced from:
      _NativeAdInteractionHandlerClient_PerformClick_m997FF068456F0B7017024F2AC196842824C471C0 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__0KaMHBxhInYeusWI1TneKQxj0hC_m2C7167466AFAE82CD96AA414C527D7F1165DF9F1 in GoogleMobileAdsNative.iOS.o
  "_GADUCreateAdLoader", referenced from:
      __za1hl4laeXrpCPhipDgCWTaGcooA__mKIQ1lKbrY4wFOSCkKFs3LPHi8R_m9476F820EABE6612AA594E7F7E60D98C0CF912AF in GoogleMobileAdsNative.iOS.o
  "_GADURecordPossibleImpressionForNativeAd", referenced from:
      _NativeAdInteractionHandlerClient_RecordImpression_mCC49A735D44CDAD268550849E7A6C8939B4C2092 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__rXvGpBRd3xFdZ8twrb5h6IStzZq_mFCC70B75ABAEA8303673B0974705304C0E79DC61 in GoogleMobileAdsNative.iOS.o
  "_GADUSetCustomNativeAdCallbacks", referenced from:
      __V1fgpHIlEfdgcIGdMwPd9AxlM8B__ctor_mE2AB3BD8E8472AC2B1E8900404D52765BC035E38 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__ibxz0UHGSQhjjx1HSuobaufiEwg_m9D996B5DDFF731C35F545231BE92A43E41857BE9 in GoogleMobileAdsNative.iOS.o
  "_GADUNativeAdIconURL", referenced from:
      __5cABXlEfG0XrM4WXXDifxKEqMEo_GetIconURL_mCE214998247CFE59F714D8F4B672CBCAAB400701 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__hXKXtP3Q0VQAhB3a9lNcUrBCFKpA_mEB0E6A8E2B0FDA8257BD8AC2EA9CCD0B33694383 in GoogleMobileAdsNative.iOS.o
  "_GADUSetCustomNativeAdUnityClient", referenced from:
      __V1fgpHIlEfdgcIGdMwPd9AxlM8B__ctor_mE2AB3BD8E8472AC2B1E8900404D52765BC035E38 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__YN2IWM1qgUZSKdBhtOJa3BJjSDH_m562836621DD8B051A151D0212A0BDD64FFB409AC in GoogleMobileAdsNative.iOS.o
  "_GADURequestNativeAd", referenced from:
      _AdLoaderClient_LoadAd_mEF18C13748B389AF8298CDF2439219E33E2E7B03 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__Nraa7uPS7MD4p9FZPayBGOLj3CD_mD284EC38797B78F3AFF7FFF82531640631743682 in GoogleMobileAdsNative.iOS.o
  "_GADUNativeAdAdChoicesLogoURL", referenced from:
      __5cABXlEfG0XrM4WXXDifxKEqMEo_GetAdChoicesLogoURL_mF39EC1C77099F032D504E03120FACBEFC3FBE61B in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__mbZHGU1NGn2yUkvG8m33kkfIAod_mA10D3DE71FAE57315DE7D2AB1FB13707B2BEA536 in GoogleMobileAdsNative.iOS.o
  "_GADUSetAdLoaderCallbacks", referenced from:
      __za1hl4laeXrpCPhipDgCWTaGcooA__H4HqX5w5COrC5eq3907KChaofbM_m86C5AB8B06BEC770026C606BAABAFB23612B5FBA in GoogleMobileAdsNative.iOS.o
  "_GADUNativeAdAssetIDMappings", referenced from:
      _NativeAdInteractionHandlerClient_BuildAssetIDMappings_mE77ADA8D7B66BDDD85757E887CEA4A234BDDA551 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__tK1sRL4sKtjp37IZU4HQcR7CeCh_m5771B26010EDE0547A78F3B9F91A3506EA4425F0 in GoogleMobileAdsNative.iOS.o
  "_GADUGetNativeAd", referenced from:
      __5cABXlEfG0XrM4WXXDifxKEqMEo__ctor_mA8227E9A289B31A9953FF25117ADC10CE752698A in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__kTWX9GpiTVfOr7dimO6CIxdb3UW_m0B9235C964005B1B0600886C8ABC04099F9C6420 in GoogleMobileAdsNative.iOS.o
  "_GADUReportTouchEventOnNativeAd", referenced from:
      _NativeAdInteractionHandlerClient_ReportTouchEvent_m08DDDACB8AE850E9C8FBE3AAAD183014BC8CE5A5 in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__PqqGVwEk5CoaTqwXLnC42G68Rep_mBDDB84244565ED90410B98ACDB53088EA1A4E106 in GoogleMobileAdsNative.iOS.o
  "_GADUSetNativeAdCallback", referenced from:
      _AdLoaderClient__puFBI5ScfwSMkuQg05abil8OXCEA_m4F1BD273C8A7D9B134CF5330BD37C42A116DE22C in GoogleMobileAdsNative.iOS.o
      __za1hl4laeXrpCPhipDgCWTaGcooA__jG2Tvm1kBshtAy8RTI7CedIoDaY_mF14C82B655B872EE530DC7226FD682D5A343376B in GoogleMobileAdsNative.iOS.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1

**Comment by mkfcga** [comment]
نسخه الفا 3 + lite با اندروید 4.4 مشکل دارن 
 16:54:54.516 21289-21289/? E/TAP_SDK_TapsellRewarde: onError javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xa1698b28: Failure in SSL library, usually a protocol error
    error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x73ed9ce0:0x00000000)

**Comment by MortezaNedaei** [comment]
> نسخه اندروید رو تست نکردم. اما ios مشکل بیلد داریم. اگر فقط از admob7.1.0 استفاده بشه هیچ خطایی در بیلد نیست. اما از آلفا 3 و lite که استفاده کردیم. با اینکه خطای ادیتور نداریم اما نمیشه بیلد گرفت. xcode:13.4.1 خطای بیلد: ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/build/Desktop/**/Libraries/libiPhone-lib.a(unwind_test_arm64.o) Undefined symbols for architecture arm64: "_GADUNativeAdCallToAction", referenced from: __5cABXlEfG0XrM4WXXDifxKEqMEo_GetCallToAction_mFEED7465E689FFE18BCA3ABB8D974FA9EB733473 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__WBjHLdy0u2OPvLcberYaz4E5lkm_mE2ABAA9E65C0BF7B227E1D80394AA6BFABAF5698 in GoogleMobileAdsNative.iOS.o "_GADUNativeAdBody", referenced from: __5cABXlEfG0XrM4WXXDifxKEqMEo_GetBody_mAFCDF87B0A649EC6356A9FB5C68B1C61F3D5720D in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__uWrZG4X0g4xz7ZcWN7vkHw29uHg_mA43438D1516D5E2A9C8151D4380A040031417955 in GoogleMobileAdsNative.iOS.o "_GADUNativeAdHeadline", referenced from: __5cABXlEfG0XrM4WXXDifxKEqMEo_GetHeadline_m1C13883E29B9F055612901F5E51051B267D4206A in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__WDCDUwJ5OfEKCY0Io3ukTaT2eSH_mA0193BF6186429BFDA921BEBC6B04190B4E4071C in GoogleMobileAdsNative.iOS.o "_GADUNativeAdMainImagesURLs", referenced from: __5cABXlEfG0XrM4WXXDifxKEqMEo_GetMainImageURLs_m30F69E4F117F035EA7D7F320DC7C3EED7A4EE6D6 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__t7yhA3nJYckCEyX1l0SAL51ip23_mEC61A2A9554853B99B04777B239096371696E648 in GoogleMobileAdsNative.iOS.o "_GADUCustomNativeAdFormatID", referenced from: __V1fgpHIlEfdgcIGdMwPd9AxlM8B_GetFormatId_m6D1516F2B74C42853B37AFBEEA07F4553133568F in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__YciJAsA6I19uIJP6mPVBeYyFmDj_m8A3AEFC12F50476C6BCF7D41C8364B9F3E14E998 in GoogleMobileAdsNative.iOS.o "_GADUPerformClickOnNativeAd", referenced from: _NativeAdInteractionHandlerClient_PerformClick_m997FF068456F0B7017024F2AC196842824C471C0 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__0KaMHBxhInYeusWI1TneKQxj0hC_m2C7167466AFAE82CD96AA414C527D7F1165DF9F1 in GoogleMobileAdsNative.iOS.o "_GADUCreateAdLoader", referenced from: __za1hl4laeXrpCPhipDgCWTaGcooA__mKIQ1lKbrY4wFOSCkKFs3LPHi8R_m9476F820EABE6612AA594E7F7E60D98C0CF912AF in GoogleMobileAdsNative.iOS.o "_GADURecordPossibleImpressionForNativeAd", referenced from: _NativeAdInteractionHandlerClient_RecordImpression_mCC49A735D44CDAD268550849E7A6C8939B4C2092 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__rXvGpBRd3xFdZ8twrb5h6IStzZq_mFCC70B75ABAEA8303673B0974705304C0E79DC61 in GoogleMobileAdsNative.iOS.o "_GADUSetCustomNativeAdCallbacks", referenced from: __V1fgpHIlEfdgcIGdMwPd9AxlM8B__ctor_mE2AB3BD8E8472AC2B1E8900404D52765BC035E38 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__ibxz0UHGSQhjjx1HSuobaufiEwg_m9D996B5DDFF731C35F545231BE92A43E41857BE9 in GoogleMobileAdsNative.iOS.o "_GADUNativeAdIconURL", referenced from: __5cABXlEfG0XrM4WXXDifxKEqMEo_GetIconURL_mCE214998247CFE59F714D8F4B672CBCAAB400701 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__hXKXtP3Q0VQAhB3a9lNcUrBCFKpA_mEB0E6A8E2B0FDA8257BD8AC2EA9CCD0B33694383 in GoogleMobileAdsNative.iOS.o "_GADUSetCustomNativeAdUnityClient", referenced from: __V1fgpHIlEfdgcIGdMwPd9AxlM8B__ctor_mE2AB3BD8E8472AC2B1E8900404D52765BC035E38 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__YN2IWM1qgUZSKdBhtOJa3BJjSDH_m562836621DD8B051A151D0212A0BDD64FFB409AC in GoogleMobileAdsNative.iOS.o "_GADURequestNativeAd", referenced from: _AdLoaderClient_LoadAd_mEF18C13748B389AF8298CDF2439219E33E2E7B03 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__Nraa7uPS7MD4p9FZPayBGOLj3CD_mD284EC38797B78F3AFF7FFF82531640631743682 in GoogleMobileAdsNative.iOS.o "_GADUNativeAdAdChoicesLogoURL", referenced from: __5cABXlEfG0XrM4WXXDifxKEqMEo_GetAdChoicesLogoURL_mF39EC1C77099F032D504E03120FACBEFC3FBE61B in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__mbZHGU1NGn2yUkvG8m33kkfIAod_mA10D3DE71FAE57315DE7D2AB1FB13707B2BEA536 in GoogleMobileAdsNative.iOS.o "_GADUSetAdLoaderCallbacks", referenced from: __za1hl4laeXrpCPhipDgCWTaGcooA__H4HqX5w5COrC5eq3907KChaofbM_m86C5AB8B06BEC770026C606BAABAFB23612B5FBA in GoogleMobileAdsNative.iOS.o "_GADUNativeAdAssetIDMappings", referenced from: _NativeAdInteractionHandlerClient_BuildAssetIDMappings_mE77ADA8D7B66BDDD85757E887CEA4A234BDDA551 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__tK1sRL4sKtjp37IZU4HQcR7CeCh_m5771B26010EDE0547A78F3B9F91A3506EA4425F0 in GoogleMobileAdsNative.iOS.o "_GADUGetNativeAd", referenced from: __5cABXlEfG0XrM4WXXDifxKEqMEo__ctor_mA8227E9A289B31A9953FF25117ADC10CE752698A in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__kTWX9GpiTVfOr7dimO6CIxdb3UW_m0B9235C964005B1B0600886C8ABC04099F9C6420 in GoogleMobileAdsNative.iOS.o "_GADUReportTouchEventOnNativeAd", referenced from: _NativeAdInteractionHandlerClient_ReportTouchEvent_m08DDDACB8AE850E9C8FBE3AAAD183014BC8CE5A5 in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__PqqGVwEk5CoaTqwXLnC42G68Rep_mBDDB84244565ED90410B98ACDB53088EA1A4E106 in GoogleMobileAdsNative.iOS.o "_GADUSetNativeAdCallback", referenced from: _AdLoaderClient__puFBI5ScfwSMkuQg05abil8OXCEA_m4F1BD273C8A7D9B134CF5330BD37C42A116DE22C in GoogleMobileAdsNative.iOS.o __za1hl4laeXrpCPhipDgCWTaGcooA__jG2Tvm1kBshtAy8RTI7CedIoDaY_mF14C82B655B872EE530DC7226FD682D5A343376B in GoogleMobileAdsNative.iOS.o ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1

پکیج ادموب لایت تپسل، فایل های مرتبط با iOS رو نداره و فقط اندروید رو ساپورت میکنه. چون در حال حاضر تپسل از iOS پشتیبانی نمیکنه.
برای رفع مشکل، ۱. میتونید پکیج آلفا و لایت تپسل رو فقط برای اندروید اضافه کنید یا ۲. به جای پکیج ادموب لایت مستقیما از پکیج [نیتیو ادموب](https://dl.google.com/googleadmobadssdk/GoogleMobileAds-native.unitypackage) استفاده کنید.
